/*
CARDINALIDADE

--> QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGÓCIO

PRIMEIRO ALGARISMO - OBRIGATORIEDADE
	0 = NÃO OBRIGATÓRIO
	1 = OBRIGATÓRIO
SEGUNDO ALGARISMO  - CARDINALIDADE
	1 = MÁXIMO DE UM
	N = MAIS DE UM
*/


/* REGRAS DE NEGÓCIO
--> ENDEREÇO OBRIGATÓRIO - CADASTRO DE SOMENTE UM;

--> TELEFONE NÃO OBRIGATÓRIO - CADASTRO DE MAIS DE UM (OPCIONAL)

*/
/*
CHAVE ESTRANGEIRA É A CHAVE PRIMÁRIA DE UMA TABELA, APLICADA COMO REFERÊNCIA
EM OUTRA TABELA.

------- > REGRAS DE ONDE SE POSICIONAR A FK (FOREIGH KEY - CHAVE ESTRANGEIRA) < -------

-- EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA 
	(QUE DEPENDA DE ALGUMA OUTRA TABELA MAIS IMPORTANTE

-- EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARÁ SEMPRE NA CARDINALIDADE N
*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR (2) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COMERC','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL
);