INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@RIUTO.COM','799879379873');

INSERT INTO CLIENTE VALUES(NULL,'CLARA','M',NULL,'234253453593');
INSERT INTO CLIENTE VALUES(NULL,'ROBERTA','F','ROBERTA@CELOKO.COM','534534379873');
INSERT INTO CLIENTE VALUES(NULL,'JOAQUINA','F','KINA_DEBOAS@VISH.COM','75666779873');
INSERT INTO CLIENTE VALUES(NULL,'JASMIN','F','JAS@MIN.COM','778877434873');
INSERT INTO CLIENTE VALUES(NULL,'JOBSON','M','JOBS@ON.COM','123123349873');
INSERT INTO CLIENTE VALUES(NULL,'RODRIGO','M','RODR@IGO.COM','7657569873');
INSERT INTO CLIENTE VALUES(NULL,'SEROTONINA','F','TOTON@NINA.COM','31212379873');
INSERT INTO CLIENTE VALUES(NULL,'ANESTESICO DA SILVA','M','ANES@TESIO.COM','1231379873');
INSERT INTO CLIENTE VALUES(NULL,'PROPILENO GLICOL','M','PROP@GLIC.COM','71231222873');

-- ENDERECO

INSERT INTO ENDERECO VALUES(NULL,'RUA ZEZIM DO DOCE','BAIRROLANDIA','PARALELANDIA','PL', 1);
INSERT INTO ENDERECO VALUES(NULL,'RUA CABULOSO','BECO DO NEGO','RIO DE SETEMBRO','RJ', 2);
INSERT INTO ENDERECO VALUES(NULL,'RUA ESQUINA','BEBIM OSWALDO','SAO PAULEIRA','SP', 3);
INSERT INTO ENDERECO VALUES(NULL,'RUA JOSEL DA SILVA','DIAGONAL 12','PELOTAS','RS', 4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPSLOCK','TRANSVERSAL','BRASOLIA','DF', 5);
INSERT INTO ENDERECO VALUES(NULL,'RUA INSERT','JOAO NAVES','99LANDIA','MG', 6);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA TRADICAO','ROSEVELT','DISNEI','DS', 7);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFREDO NASCEER','ITIQUIRA','FLORIPA','FL', 8);
INSERT INTO ENDERECO VALUES(NULL,'RUA ESTAQUIO','ITATIAIA','CHAPADA DOS VEADEROS','CH', 9);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO LOKERA','CERAMICA','PARALELANDIA','PL', 10);

-- TELEFONE

INSERT INTO TELEFONE VALUES(NULL,'CEL','99876545', 1);
INSERT INTO TELEFONE VALUES(NULL,'RES','33234545', 1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33777665', 2);
INSERT INTO TELEFONE VALUES(NULL,'COMERC','33376545', 2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','55334445', 3);
INSERT INTO TELEFONE VALUES(NULL,'COMERC','33876545', 3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99432341', 4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','43765421', 5);
INSERT INTO TELEFONE VALUES(NULL,'RES','33844445', 5);

-- SELEÇÃO, PROJEÇÃO E JUNÇÃO --

--> PROJEÇÃO É TUDO QUE SE QUER VER NA TELA

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW() AS TEMPO FROM CLIENTE;

--> SELEÇÃO É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS
-- DE UMA TABELA; A CLAUSULA DE SELEÇÃO É WHERE

SELECT NOME, SEXO, EMAIL --> PROJEÇÃO
FROM CLIENTE --> ORIGEM DOS DADOS
WHERE SEXO = 'F'; --> SELEÇÃO

SELECT NUMERO --> PROJEÇÃO
FROM TELEFONE --> ORIGEM DOS DADOS
WHERE TIPO = 'CEL'; --> SELEÇÃO