INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@RIUTO.COM','799879379873');

INSERT INTO CLIENTE VALUES(NULL,'CLARA','M',NULL,'234253453593');
INSERT INTO CLIENTE VALUES(NULL,'ROBERTA','F','ROBERTA@CELOKO.COM','534534379873');
INSERT INTO CLIENTE VALUES(NULL,'JOAQUINA','F','KINA_DEBOAS@VISH.COM','75666779873');
INSERT INTO CLIENTE VALUES(NULL,'JASMIN','F','JAS@MIN.COM','778877434873');
INSERT INTO CLIENTE VALUES(NULL,'JOBSON','M','JOBS@ON.COM','123123349873');
INSERT INTO CLIENTE VALUES(NULL,'RODRIGO','M','RODR@IGO.COM','7657569873');
INSERT INTO CLIENTE VALUES(NULL,'SEROTONINA','F','TOTON@NINA.COM','31212379873');
INSERT INTO CLIENTE VALUES(NULL,'ANESTESICO DA SILVA','M','ANES@TESIO.COM','1231379873');
INSERT INTO CLIENTE VALUES(NULL,'PROPILENO GLICOL','M','PROP@GLIC.COM','71231222873');

-- ENDERECO

INSERT INTO ENDERECO VALUES(NULL,'RUA ZEZIM DO DOCE','BAIRROLANDIA','PARALELANDIA','PL', 1);
INSERT INTO ENDERECO VALUES(NULL,'RUA CABULOSO','BECO DO NEGO','RIO DE SETEMBRO','RJ', 2);
INSERT INTO ENDERECO VALUES(NULL,'RUA ESQUINA','BEBIM OSWALDO','SAO PAULEIRA','SP', 3);
INSERT INTO ENDERECO VALUES(NULL,'RUA JOSEL DA SILVA','DIAGONAL 12','PELOTAS','RS', 4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPSLOCK','TRANSVERSAL','BRASOLIA','DF', 5);
INSERT INTO ENDERECO VALUES(NULL,'RUA INSERT','JOAO NAVES','99LANDIA','MG', 6);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA TRADICAO','ROSEVELT','DISNEI','DS', 7);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFREDO NASCEER','ITIQUIRA','FLORIPA','FL', 8);
INSERT INTO ENDERECO VALUES(NULL,'RUA ESTAQUIO','ITATIAIA','CHAPADA DOS VEADEROS','CH', 9);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO LOKERA','CERAMICA','PARALELANDIA','PL', 10);

-- TELEFONE

INSERT INTO TELEFONE VALUES(NULL,'CEL','99876545', 1);
INSERT INTO TELEFONE VALUES(NULL,'RES','33234545', 1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33777665', 2);
INSERT INTO TELEFONE VALUES(NULL,'COMERC','33376545', 2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','55334445', 3);
INSERT INTO TELEFONE VALUES(NULL,'COMERC','33876545', 3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99432341', 4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','43765421', 5);
INSERT INTO TELEFONE VALUES(NULL,'RES','33844445', 5);

-- SELEÇÃO, PROJEÇÃO E JUNÇÃO --

--> PROJEÇÃO É TUDO QUE SE QUER VER NA TELA

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW() AS TEMPO FROM CLIENTE;

--> SELEÇÃO É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS
-- DE UMA TABELA; A CLAUSULA DE SELEÇÃO É WHERE

SELECT NOME, SEXO, EMAIL --> PROJEÇÃO
FROM CLIENTE --> ORIGEM DOS DADOS
WHERE SEXO = 'F'; --> SELEÇÃO

SELECT NUMERO --> PROJEÇÃO
FROM TELEFONE --> ORIGEM DOS DADOS
WHERE TIPO = 'CEL'; --> SELEÇÃO

/* JUNÇÃO DE TABELAS -> JOIN */

-- INICIAMOS PELA DEFINIÇÃO DO QUE QUEREMOS OBTER

SELECT NOME, EMAIL, IDCLIENTE
FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

--> QUANDO REALIZAMOS UM INNER JOIN, JUNTAMOS AS COLUNAS
--- QUE SERÃO COMPARADAS. (OS IDs)

SELECT NOME, SEXO, BAIRRO, CIDADE --> PROJEÇÃO
FROM CLIENTE --> ORIGEM
	INNER JOIN ENDERECO --> JUNÇÃO
	ON IDCLIENTE = ID_CLIENTE --> CONDIÇÃO ONDE COLUNAPK = COLUNAFK
WHERE SEXO = "F"; --> SELEÇÃO
/* 
+------------+------+---------------+--------------+
| NOME       | SEXO | BAIRRO        | CIDADE       |
+------------+------+---------------+--------------+
| ROBERTA    | F    | BEBIM OSWALDO | SAO PAULEIRA |
| JOAQUINA   | F    | DIAGONAL 12   | PELOTAS      |
| JASMIN     | F    | TRANSVERSAL   | BRASOLIA     |
| SEROTONINA | F    | ITIQUIRA      | FLORIPA      |
+------------+------+---------------+--------------+
*/

--> TRAGA NOME, SEXO, EMAIL, TIPO, NUMERO


SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE;
/*
+----------+------+----------------------+--------+----------+
| NOME     | SEXO | EMAIL                | TIPO   | NUMERO   |
+----------+------+----------------------+--------+----------+
| JOAO     | M    | JOAO@RIUTO.COM       | CEL    | 99876545 |
| JOAO     | M    | JOAO@RIUTO.COM       | RES    | 33234545 |
| CLARA    | M    | NULL                 | CEL    | 33777665 |
| CLARA    | M    | NULL                 | COMERC | 33376545 |
| ROBERTA  | F    | ROBERTA@CELOKO.COM   | CEL    | 55334445 |
| ROBERTA  | F    | ROBERTA@CELOKO.COM   | COMERC | 33876545 |
| JOAQUINA | F    | KINA_DEBOAS@VISH.COM | CEL    | 99432341 |
| JASMIN   | F    | JAS@MIN.COM          | CEL    | 43765421 |
| JASMIN   | F    | JAS@MIN.COM          | RES    | 33844445 |
+----------+------+----------------------+--------+----------+
*/

--> O RESULTADO É 1 PARA N, ENTÃO QUEM POSSUIR MAIS DE UM NÚMERO
-- DE TELEFONE CADASTRADO APARECERÁ EM LINHAS "DUPLICADAS"

SELECT NOME, EMAIL, NUMERO, CIDADE, ESTADO
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;
--> ERROR 1052 (23000): Column 'ID_CLIENTE' in on clause is ambiguous


SELECT CLIENTE.NOME, CLIENTE.EMAIL, TELEFONE.NUMERO, ENDERECO.CIDADE, ENDERECO.ESTADO
FROM CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE;

+----------+----------------------+----------+-----------------+--------+
| NOME     | EMAIL                | NUMERO   | CIDADE          | ESTADO |
+----------+----------------------+----------+-----------------+--------+
| JOAO     | JOAO@RIUTO.COM       | 99876545 | PARALELANDIA    | PL     |
| JOAO     | JOAO@RIUTO.COM       | 33234545 | PARALELANDIA    | PL     |
| CLARA    | NULL                 | 33777665 | RIO DE SETEMBRO | RJ     |
| CLARA    | NULL                 | 33376545 | RIO DE SETEMBRO | RJ     |
| ROBERTA  | ROBERTA@CELOKO.COM   | 55334445 | SAO PAULEIRA    | SP     |
| ROBERTA  | ROBERTA@CELOKO.COM   | 33876545 | SAO PAULEIRA    | SP     |
| JOAQUINA | KINA_DEBOAS@VISH.COM | 99432341 | PELOTAS         | RS     |
| JASMIN   | JAS@MIN.COM          | 43765421 | BRASOLIA        | DF     |
| JASMIN   | JAS@MIN.COM          | 33844445 | BRASOLIA        | DF     |
+----------+----------------------+----------+-----------------+--------+

OU

--> APLICANDO ALIAS

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

+----------+------+---------------+-----------------+--------+----------+
| NOME     | SEXO | BAIRRO        | CIDADE          | TIPO   | NUMERO   |
+----------+------+---------------+-----------------+--------+----------+
| JOAO     | M    | BAIRROLANDIA  | PARALELANDIA    | CEL    | 99876545 |
| JOAO     | M    | BAIRROLANDIA  | PARALELANDIA    | RES    | 33234545 |
| CLARA    | M    | BECO DO NEGO  | RIO DE SETEMBRO | CEL    | 33777665 |
| CLARA    | M    | BECO DO NEGO  | RIO DE SETEMBRO | COMERC | 33376545 |
| ROBERTA  | F    | BEBIM OSWALDO | SAO PAULEIRA    | CEL    | 55334445 |
| ROBERTA  | F    | BEBIM OSWALDO | SAO PAULEIRA    | COMERC | 33876545 |
| JOAQUINA | F    | DIAGONAL 12   | PELOTAS         | CEL    | 99432341 |
| JASMIN   | F    | TRANSVERSAL   | BRASOLIA        | CEL    | 43765421 |
| JASMIN   | F    | TRANSVERSAL   | BRASOLIA        | RES    | 33844445 |
+----------+------+---------------+-----------------+--------+----------+

--> REFORÇANDO O CONHECIMENTO:
-- TRAZER: NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO

SELECT CLI.NOME, CLI.SEXO, ENDR.BAIRRO, ENDR.CIDADE, TEL.TIPO, TEL.NUMERO
FROM CLIENTE CLI
INNER JOIN ENDERECO ENDR
ON CLI.IDCLIENTE = ENDR.ID_CLIENTE
INNER JOIN TELEFONE TEL
ON CLI.IDCLIENTE = TEL.ID_CLIENTE;
+----------+------+---------------+-----------------+--------+----------+
| NOME     | SEXO | BAIRRO        | CIDADE          | TIPO   | NUMERO   |
+----------+------+---------------+-----------------+--------+----------+
| JOAO     | M    | BAIRROLANDIA  | PARALELANDIA    | CEL    | 99876545 |
| JOAO     | M    | BAIRROLANDIA  | PARALELANDIA    | RES    | 33234545 |
| CLARA    | M    | BECO DO NEGO  | RIO DE SETEMBRO | CEL    | 33777665 |
| CLARA    | M    | BECO DO NEGO  | RIO DE SETEMBRO | COMERC | 33376545 |
| ROBERTA  | F    | BEBIM OSWALDO | SAO PAULEIRA    | CEL    | 55334445 |
| ROBERTA  | F    | BEBIM OSWALDO | SAO PAULEIRA    | COMERC | 33876545 |
| JOAQUINA | F    | DIAGONAL 12   | PELOTAS         | CEL    | 99432341 |
| JASMIN   | F    | TRANSVERSAL   | BRASOLIA        | CEL    | 43765421 |
| JASMIN   | F    | TRANSVERSAL   | BRASOLIA        | RES    | 33844445 |
+----------+------+---------------+-----------------+--------+----------+

--> CONCEITOS TÉCNICOS SQL

01 --> DML - DATA MANIPULATION LANGUAGE
02 --> DDL - DATA DEFINITION LANGUAGE
03 --> DCL - DATA CONTROL LANGUAGE
04 --> TCL - TRANSACTION CONTROL LANGUAGE

01 --> DML

--> INSERT

INSERT INTO CLIENTE VALUES(NULL, 'PAULA PADRÃO', 'M', NULL, '3478923478');
INSERT INTO ENDERECO VALUES(NULL, 'RUA CELOKO NAVES','SÃO JÔA1','COPANABANCA','DJ',11);

SELECT * FROM CLIENTE;

--> FILTROS

SELECT * FROM CLIENTE
WHERE SEXO = 'M'; --> ERRO 

--> UPDATE

SELECT * FROM CLIENTE --> SEMPRE DEVEMOS CHECAR ANTES DE REALIZAR A OPERAÇÃO.
WHERE IDCLIENTE = 11;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 11;

UPDATE CLIENTE
SET EMAIL = 'ANAPAULA@PADRONES.COM'
WHERE IDCLIENTE = 11;

--> DELETE

INSERT INTO CLIENTE VALUES(NULL,'ERRADAO ID 12','M',NULL,'EREASEME');

SELECT * FROM CLIENTE WHERE IDCLIENTE = 12;

DELETE FROM CLIENTE WHERE IDCLIENTE = 12;