/* RELATORIO GERAL DE TODOS OS CLIENTES */
	SELECT * FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE;
	
	---------------------------------------------------------
	
	SELECT C.NOME, C.SEXO, C.EMAIL, E.CIDADE, E.ESTADO, E.BAIRRO, T.NUMERO, C.CPF FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	ORDER BY SEXO;
	
/* RELATORIO - SOMENTE HOMENS */
	SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, E.CIDADE, E.BAIRRO, E.CIDADE, T.NUMERO, T.TIPO FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	WHERE C.SEXO = "M";
/* RELATORIO - SOMENTE MULHERES */
	SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, E.CIDADE, E.BAIRRO, E.CIDADE, T.NUMERO, T.TIPO FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	WHERE C.SEXO = 'F';
/* QUANTIDADE DE HOMENS E MULHERES*/
	SELECT SEXO,
	COUNT(*) AS QTD_SEXO_F,
	COUNT(*) AS QTD_SEXO_M
	FROM CLIENTE
	GROUP BY SEXO;
	--> MELHORANDO UM POUCO:
	SELECT SEXO,
	COUNT(*) AS QTD	
	FROM CLIENTE
	GROUP BY SEXO;
/* IDS E EMAILS DAS MULHERES QUE MORAM NO CENTRO DO RJ E NÃO TEM CELULAR*/
	SELECT CLI.IDCLIENTE, CLI.EMAIL, LOC.CIDADE, LOC.ESTADO, TEL.TIPO FROM CLIENTE CLI
	INNER JOIN TELEFONE TEL
	ON CLI.IDCLIENTE = TEL.ID_CLIENTE
	INNER JOIN ENDERECO LOC
	ON CLI.IDCLIENTE = LOC.ID_CLIENTE
	WHERE  NOT TEL.TIPO='CEL' AND CLI.SEXO ='F' AND LOC.CIDADE='RIO DE JANEIRO';
/* RELATORIO GERAL DE TODOS OS CLIENTES (TELEFONE E ENDERECO) */
	SELECT C.NOME, TEL.TIPO, TEL.NUMERO, LOC.CIDADE, LOC.BAIRRO, LOC.ESTADO FROM CLIENTE C
	INNER JOIN TELEFONE TEL
	ON C.IDCLIENTE = TEL.ID_CLIENTE
	INNER JOIN ENDERECO LOC
	ON C.IDCLIENTE = LOC.ID_CLIENTE;

--> ATUALIZANDO CLIENTE PARA CEL = NULL
SELECT ID_CLIENTE FROM TELEFONE
WHERE ID_CLIENTE = '3'; 

UPDATE TELEFONE 
SET NUMERO ='' 
WHERE ID_CLIENTE=3;

DESC CLIENTE;
DESC ENDERECO;
DESC TELEFONE;