Exercícios - Aula de banco de dados - Udemy

001 - Livraria

/* CRIAÇÃO DO BANCO DE DADOS */

CREATE DATABASE LIVRARIA;
USE LIVRARIA;

COMPOSIÇÃO DA TABELA: LIVROS
CREATE TABLE LIVROS(
	TITULO VARCHAR(42),
	AUTOR VARCHAR(42),
	SEXO CHAR(1),
	NUM_PAG INT(4),
	EDITORA VARCHAR(42),
	PRECO DECIMAL(4,2),
	UF_EDITORA VARCHAR(42),
	ANO_PUB DATE
);

/* definindo as regras */

ALTER TABLE LIVROS 
CHANGE ANO_PUB ANO_PUB YEAR;

/*INSERÇÃO DE DADOS*/

INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('CAVALEIRO REAL','ANA CLAUDIA','F',465,'ATLAS',49.90,'RJ',2009);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('SQL PARA LEIGOS','JOÃO NUNES','M',450,'ADDISON',98,'SP',2018);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390,'BETA', 78.99, 'RJ', 2018);
/*PARA INSERIR O PREÇO DE HABITOS SAUDAVEIS, TIVE QUE MODIFICAR O TAMANHO DE ARMAZENAMENTO*/
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('HABITOS SAUDAVEIS', 'EDUARDO SANTOS', 'M', 630,'BETA', 150.98, 'RJ', 2019);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60, 'MG', 2016);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310, 'INSIGNIA', 100, 'ES', 2015);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('PARA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 78.98, 'ES', 2011);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('COPAS INESQUECIVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', 2018);
INSERT INTO LIVROS(TITULO, AUTOR, SEXO, NUM_PAG, EDITORA, PRECO, UF_EDITORA, ANO_PUB) VALUES('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58, 'SP', 2017);
Escopo: Apenas os dados iniciais da tabela Clientes;

1 – Trazer todos os dados.
	SELECT * FROM LIVROS;
2 – Trazer o nome do livro e o nome da editora
	SELECT TITULO, EDITORA FROM LIVROS;
3 – Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino.
	SELECT TITULO, UF_EDITORA FROM LIVROS WHERE SEXO = "M";
4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino.
	SELECT TITULO, NUM_PAG FROM LIVROS WHERE SEXO ="F";
5 – Trazer os valores dos livros das editoras de São Paulo.
	SELECT PRECO FROM LIVROS WHERE UF_EDITORA = 'SP';
6 – Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).
	SELECT AUTOR FROM LIVROS WHERE SEXO ="M" AND (UF_EDITORA ="RJ" OR UF_EDITORA ="SP");



-------------------- CONCEITOS --------------------------------
--> MODIFICAR NOME E TIPO DE DADO DA COLUNA
ALTER TABLE nome_da_tabela
CHANGE nome_atual novo_nome [Tipo de Dados];


-- RESUMO AULAS SOBRE UPDATE AND DELETE
/* 
-- DEVEMOS VERIFICAR A QUANTIDADE DE RETORNO DE UMA CONSULTA, UTILIZANDO O COUNT(*)
	EX: SELECT COUNT(*) FROM CLIENTE --> TOTAL CLIENTE
		SELECT COUNT(*) FROM CLIENTE WERE NOME = 'JOAO';
-- ANTES DE REALIZAR AS OPERAÇÕES DE DELETE OU UPDATE, DEVEMOS VERIFICAR SE O SELECT TRAZ O QUE DESEJAMOS
EXCLUIR DE FATO; 
-- A CLAUSULA WHERE DEVE SER UTILIZADA EM AMBAS AS OPERAÇÕES;
-- WHERE PODE SER UTILIZADO EM CONJUNTO COM AS DEMAIS CLAUSULAS DE CONSULTA E DE LÓGICA;
*/

-- REALIZANDO UPDATE DE FORMA CORRETA:
UPDATE CLIENTE SET EMAIL = 'JR00.DAT@GMAIL.COM' WHERE NOME = 'JOAO';

-- LEMBRANDO QUE PODEMOS VERIFICAR COM UM SELECT, SE O UPDATE SERÁ REALMENTE ONDE DESEJAMOS.